-- MySQL Script generated by MySQL Workbench
-- Thu Dec 29 14:38:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema train_station_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema train_station_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `train_station_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `train_station_db` ;

-- -----------------------------------------------------
-- Table `train_station_db`.`Passanger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station_db`.`Passanger` (
  `Passanger_ID` INT UNSIGNED NOT NULL,
  `Passanger_name` VARCHAR(50) NOT NULL,
  `Passenger_address` VARCHAR(40) NOT NULL,
  `Passanger_gender` ENUM('Male', 'Female') NULL DEFAULT NULL,
  PRIMARY KEY (`Passanger_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `train_station_db`.`Trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station_db`.`Trains` (
  `Train_NO` VARCHAR(25) NOT NULL,
  `Fare` FLOAT NOT NULL,
  `Source` CHAR(40) NOT NULL,
  `Destination` CHAR(40) NOT NULL,
  `Weekdays_available` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`Train_NO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `train_station_db`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station_db`.`Ticket` (
  `Ticket_ID` INT UNSIGNED NOT NULL,
  `Ticket_Status` ENUM('Confirm', 'Not Confirm') NULL DEFAULT NULL,
  `Train_NO` VARCHAR(25) NOT NULL,
  `Passanger_ID` INT UNSIGNED NOT NULL,
  `Passanger_Passanger_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Ticket_ID`),
  INDEX `Train_NO` (`Train_NO` ASC) VISIBLE,
  INDEX `fk_Ticket_Passanger1_idx` (`Passanger_Passanger_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Ticket_Passanger1`
    FOREIGN KEY (`Passanger_Passanger_ID`)
    REFERENCES `train_station_db`.`Passanger` (`Passanger_ID`),
  CONSTRAINT `ticket_ibfk_1`
    FOREIGN KEY (`Train_NO`)
    REFERENCES `train_station_db`.`Trains` (`Train_NO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `train_station_db`.`Train_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `train_station_db`.`Train_Status` (
  `Seats_available` INT NOT NULL,
  `seats_booked` INT NOT NULL,
  `Train_NO` VARCHAR(25) NOT NULL,
  INDEX `Train_NO` (`Train_NO` ASC) VISIBLE,
  CONSTRAINT `train_status_ibfk_1`
    FOREIGN KEY (`Train_NO`)
    REFERENCES `train_station_db`.`Trains` (`Train_NO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
